---
title: "Sam's Strava Hikes"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries
```{r}
library(rStrava)
library(tidyverse)
library(httr)
```

# Create authentication token 
```{r}
app_name <- "SamHeatmaps" # chosen by user 
strava_client_id <- "82403" # an integer, assigned by Strava
strava_secret <- "8efb25f76d20b40a5e331de35e3e0436812d524d" # an alphanumeric secret, assigned by Strava

# create the authentication token
stoken <- httr::config(token = strava_oauth(app_name, strava_client_id, strava_secret,
                                            app_scope = "activity:read_all"))

# # create oauth app
# strava_app <- oauth_app(appname = app_name, 
#                         key = Sys.getenv("strava_client_id"), 
#                         secret = Sys.getenv("strava_secret"))
# 
# # describe oauth endpoint
# strava_endpoint <-  oauth_endpoint(request = NULL,
#                                    authorize = "https://www.strava.com/oauth/authorize",
#                                    access = "https://www.strava.com/oauth/token")
# 
# # generate oauth2.0 token
# oauth2.0_token(strava_endpoint, strava_app,
#                scope = "activity:read_all,activity:read,profile:read_all",
#                type = NULL, use_oob = FALSE, 
#                as_header = FALSE, use_basic_auth = FALSE, 
#                cache = FALSE)

```

# Get activities
```{r}
activities_url <- parse_url("https://www.strava.com/api/v3/athlete/activities")

act_vec <- vector(mode = "list")
df_act <- tibble::tibble(init = "init")
i <- 1L

while (nrow(df_act) != 0) {
  r <- activities_url %>%
    modify_url(query = list(
      access_token = sig$credentials$access_token[[1]],
      page = i
    )) %>%
    GET()

  df_act <- content(r, as = "text") %>%
    fromJSON(flatten = TRUE) %>%
    as_tibble()
  if (nrow(df_act) != 0)
    act_vec[[i]] <- df_act
  i <- i + 1L
}

df_activities <- act_vec %>%
  bind_rows() %>%
  mutate(start_date = ymd_hms(start_date))

```











-------------------------------------------------
# Define App
```{r}
define_strava_app <- function() {
  oauth_app(
    appname = app_name,
    key = Sys.getenv(client_id),
    secret = Sys.getenv(secret)
  )
}

```

# Define endpoint
```{r}
define_strava_endpoint <- function() {
  oauth_endpoint(request = NULL,
                 authorize = "https://www.strava.com/oauth/authorize",
                 access = "https://www.strava.com/oauth/token")
}
```

# Final authentication step
```{r}
define_strava_sig <- function(endpoint, app) {
  oauth2.0_token(
    endpoint,
    app,
    scope = "activity:read_all,activity:read,profile:read_all",
    type = NULL,
    use_oob = FALSE,
    as_header = FALSE,
    use_basic_auth = FALSE,
    cache = FALSE
  )
}
```

# Load all activities
```{r}
read_all_activities <- function(sig) {
  activities_url <- parse_url("https://www.strava.com/api/v3/athlete/activities")

  act_vec <- vector(mode = "list")
  df_act <- tibble::tibble(init = "init")
  i <- 1L

  while (nrow(df_act) != 0) {
    r <- activities_url %>%
      modify_url(query = list(
        access_token = sig$credentials$access_token[[1]],
        page = i
      )) %>%
      GET()

    df_act <- content(r, as = "text") %>%
      fromJSON(flatten = TRUE) %>%
      as_tibble()
    if (nrow(df_act) != 0)
      act_vec[[i]] <- df_act
    i <- i + 1L
  }

  df_activities <- act_vec %>%
    bind_rows() %>%
    mutate(start_date = ymd_hms(start_date))
}
```

